name: docx_to_text
description: A small Dart package for converting docx files (Microsoft Word) to string.
version: 1.0.1
homepage: https://github.com/StarProxima
repository: https://github.com/StarProxima/docx_to_text

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  archive: ">=4.0.0 <5.0.0"
  xml: ">=6.2.2 <7.0.0"
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

